apiVersion: v1alpha
kind: Project
metadata:
  name: Checks
spec:
  repository:
    url: "git@github.com:jesusmarzor/Peluqueria.git"
    run: true
    run_on:
      - branches
      - tags
    pipeline_file: ".semaphore/semaphore.yml"

    status:
      pipeline_files:
        - path: ".semaphore/semaphore.yml"
          level: "block"